<?php
include_once('modelcampur.php');
include_once('modelkaryawan.php');
include_once('modeloffice.php');
session_start();
include_once('controllercampur.php');
include_once('controllerkaryawan.php');
include_once('controlleroffice.php');
?>